# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:


{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # boot.supportedFilesystems = [ "ntfs" ]; # already defined in confiruration.nix

  services.fstrim.enable = true; # for SSD disk drive

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" "wl" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/55684f78-0756-4962-850e-edc95cfbc9f6";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0AFB-7D3C";
      fsType = "vfat";
    };

  fileSystems."/media/mydrive" =
    { device = "/dev/disk/by-uuid/1e0837b9-6a16-4a6d-aa6a-8efb05941d55";
      fsType = "ext4";
    };


   fileSystems."/media/mydata" =
    { device = "/dev/disk/by-uuid/5F89883D62920513";
      fsType = "ntfs-3g";
      options = [ "rw" "uid=1000"]; # run: id -u kolay
    };

    

  swapDevices =
    [ { device = "/dev/disk/by-uuid/4939ea06-66f7-4371-b364-6e2bc1d2ccce"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.vboxnet0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
